apiVersion: apps/v1
kind: Deployment
metadata:
  name: gitops-microservice
  namespace: swati
spec:
  replicas: 1
  selector:
    matchLabels:
      app: gitops-microservice
  template:
    metadata:
      labels:
        app: gitops-microservice
    spec:
      containers:
        - name: gitops-microservice
          image: swati9455/gitops-microservice-demo:d4271ae
          ports:
            - containerPort: 80
          env:
            - name: VERSION
              value: "v2"
            - name: ENV
              value: "development"
